//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Models.Components;
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An object containing information about the User&apos;s account and balance
    /// </summary>
    public class AccountResponse
    {

        /// <summary>
        /// User Login
        /// </summary>
        [JsonProperty("login")]
        public string? Login { get; set; }

        /// <summary>
        /// Account type
        /// </summary>
        [JsonProperty("account_type")]
        public AccountType? AccountType { get; set; }

        /// <summary>
        /// Acount limit
        /// </summary>
        [JsonProperty("limit")]
        public float? Limit { get; set; }

        /// <summary>
        /// Current account balance
        /// </summary>
        [JsonProperty("credit")]
        public float? Credit { get; set; }

        /// <summary>
        /// Subaccount credit balance (null if unlimited)
        /// </summary>
        [JsonProperty("subcredit")]
        public float? Subcredit { get; set; } = null;

        /// <summary>
        /// Account currency
        /// </summary>
        [JsonProperty("currency")]
        public string? Currency { get; set; }

        /// <summary>
        /// User name and surname
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Is main account?
        /// </summary>
        [JsonProperty("is_main")]
        public bool? IsMain { get; set; }
    }
}