//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Models.Components;
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An object containing information about results of cancelling single message
    /// </summary>
    public class CancelledMessage
    {

        /// <summary>
        /// Message ID
        /// </summary>
        [JsonProperty("id")]
        public long? Id { get; set; }

        /// <summary>
        /// Status of cancellation (204 if cancelled successfully or error status code)
        /// </summary>
        [JsonProperty("status")]
        public long? Status { get; set; }

        /// <summary>
        /// An object that complies with RFC 9457 containing information about a request error
        /// </summary>
        [JsonProperty("error")]
        public Models.Components.ErrorResponse? Error { get; set; } = null;
    }
}