//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// An object with the properties of the received message
    /// </summary>
    public class IncomingMessage
    {

        /// <summary>
        /// Unique identifier of incoming message
        /// </summary>
        [JsonProperty("id")]
        public long? Id { get; set; }

        /// <summary>
        /// Login of the account (sub-account) on which the message was received
        /// </summary>
        [JsonProperty("login")]
        public string? Login { get; set; }

        /// <summary>
        /// Recipient number (or service name)
        /// </summary>
        [JsonProperty("recipient")]
        public string? Recipient { get; set; }

        /// <summary>
        /// Message sender number (or alphanumeric name)
        /// </summary>
        [JsonProperty("sender")]
        public string? Sender { get; set; }

        /// <summary>
        /// Sender name (matched with phonebook)
        /// </summary>
        [JsonProperty("phonebook_sender_name")]
        public string? PhonebookSenderName { get; set; } = null;

        /// <summary>
        /// Date and time of message receipt in ISO 8601 format
        /// </summary>
        [JsonProperty("date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Received message content
        /// </summary>
        [JsonProperty("message")]
        public string? Message { get; set; }

        /// <summary>
        /// Dedicated Mobile Originated service number (if the message was received on this number)
        /// </summary>
        [JsonProperty("dedicated_number")]
        public string? DedicatedNumber { get; set; } = null;

        /// <summary>
        /// Dedicated Mobile Originated service prefix (if the message was received on this number with such prefix)
        /// </summary>
        [JsonProperty("dedicated_prefix")]
        public string? DedicatedPrefix { get; set; } = null;
    }
}