//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An object defining the message recipient telephone number with the message&apos;s custom identifier assigned by the User
    /// </summary>
    public class PhoneNumberWithCid
    {

        /// <summary>
        /// A telephone number in international format (with a plus sign and the country code at the beginning, e.g. +48 for Poland)
        /// </summary>
        [JsonProperty("nr")]
        public string Nr { get; set; } = default!;

        /// <summary>
        /// Custom message ID assigned by the User
        /// </summary>
        [JsonProperty("cid")]
        public string? Cid { get; set; }
    }
}