//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// &apos;Ping&apos; response object
    /// </summary>
    public class PingResponse
    {

        /// <summary>
        /// API service status: OK - API available, ERR - API unavailable
        /// </summary>
        [JsonProperty("status")]
        public string? Status { get; set; }

        /// <summary>
        /// Current API Version
        /// </summary>
        [JsonProperty("version")]
        public string? Version { get; set; }

        /// <summary>
        /// Was the connection established with the test system (SANDBOX)?
        /// </summary>
        [JsonProperty("sandbox")]
        public bool? Sandbox { get; set; }
    }
}