//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An object with the properties of the message sender
    /// </summary>
    public class Sender
    {

        /// <summary>
        /// Message sender name
        /// </summary>
        [JsonProperty("sender")]
        public string SenderValue { get; set; } = default!;

        /// <summary>
        /// Sender name status
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; } = default!;

        /// <summary>
        /// Is the sender default?
        /// </summary>
        [JsonProperty("is_default")]
        public bool IsDefault { get; set; } = default!;
    }
}