//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An object with the properties of the message sender
    /// </summary>
    public class SenderInput
    {

        /// <summary>
        /// Message sender name
        /// </summary>
        [JsonProperty("sender")]
        public string Sender { get; set; } = default!;

        /// <summary>
        /// Description of the purpose of the sender name (required when adding new sender name)
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; } = default!;
    }
}