//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Models.Components;
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SmsMessageRecipientsType
    {
        private SmsMessageRecipientsType(string value) { Value = value; }

        public string Value { get; private set; }

        public static SmsMessageRecipientsType Str { get { return new SmsMessageRecipientsType("str"); } }

        public static SmsMessageRecipientsType ArrayOfStr { get { return new SmsMessageRecipientsType("arrayOfStr"); } }

        public static SmsMessageRecipientsType PhoneNumberWithCid { get { return new SmsMessageRecipientsType("PhoneNumberWithCid"); } }

        public static SmsMessageRecipientsType ArrayOfPhoneNumberWithCid { get { return new SmsMessageRecipientsType("arrayOfPhoneNumberWithCid"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SmsMessageRecipientsType v) { return v.Value; }
        public static SmsMessageRecipientsType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "arrayOfStr": return ArrayOfStr;
                case "PhoneNumberWithCid": return PhoneNumberWithCid;
                case "arrayOfPhoneNumberWithCid": return ArrayOfPhoneNumberWithCid;
                default: throw new ArgumentException("Invalid value for SmsMessageRecipientsType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SmsMessageRecipientsType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The recipient number or multiple recipients numbers of single message. To set one recipient, please use `SmsMessageRecipients.CreateStr()` method simply passing to it a `string` with his phone number. To set multiple recipients, please use `SmsMessageRecipients.CreateArrayOfStr()` method passing to it `List&lt;string&gt;`. Optionally you can also set custom id (user identifier) for each message - use `SmsMessageRecipients.CreatePhoneNumberWithCid()` method passing `PhoneNumberWithCid` object (in case of single recipient) or `SmsMessageRecipients.CreateArrayOfPhoneNumberWithCid()` method passing List&lt;PhoneNumberWithCid&gt; (in case of multiple recipients).
    /// </summary>
    [JsonConverter(typeof(SmsMessageRecipients.SmsMessageRecipientsConverter))]
    public class SmsMessageRecipients
    {
        public SmsMessageRecipients(SmsMessageRecipientsType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public PhoneNumberWithCid? PhoneNumberWithCid { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<PhoneNumberWithCid>? ArrayOfPhoneNumberWithCid { get; set; }

        public SmsMessageRecipientsType Type { get; set; }
        public static SmsMessageRecipients CreateStr(string str)
        {
            SmsMessageRecipientsType typ = SmsMessageRecipientsType.Str;

            SmsMessageRecipients res = new SmsMessageRecipients(typ);
            res.Str = str;
            return res;
        }
        public static SmsMessageRecipients CreateArrayOfStr(List<string> arrayOfStr)
        {
            SmsMessageRecipientsType typ = SmsMessageRecipientsType.ArrayOfStr;

            SmsMessageRecipients res = new SmsMessageRecipients(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }
        public static SmsMessageRecipients CreatePhoneNumberWithCid(PhoneNumberWithCid phoneNumberWithCid)
        {
            SmsMessageRecipientsType typ = SmsMessageRecipientsType.PhoneNumberWithCid;

            SmsMessageRecipients res = new SmsMessageRecipients(typ);
            res.PhoneNumberWithCid = phoneNumberWithCid;
            return res;
        }
        public static SmsMessageRecipients CreateArrayOfPhoneNumberWithCid(List<PhoneNumberWithCid> arrayOfPhoneNumberWithCid)
        {
            SmsMessageRecipientsType typ = SmsMessageRecipientsType.ArrayOfPhoneNumberWithCid;

            SmsMessageRecipients res = new SmsMessageRecipients(typ);
            res.ArrayOfPhoneNumberWithCid = arrayOfPhoneNumberWithCid;
            return res;
        }

        public class SmsMessageRecipientsConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SmsMessageRecipients);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new SmsMessageRecipients(SmsMessageRecipientsType.PhoneNumberWithCid)
                    {
                        PhoneNumberWithCid = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<PhoneNumberWithCid>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(PhoneNumberWithCid), new SmsMessageRecipients(SmsMessageRecipientsType.PhoneNumberWithCid), "PhoneNumberWithCid"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new SmsMessageRecipients(SmsMessageRecipientsType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new SmsMessageRecipients(SmsMessageRecipientsType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new SmsMessageRecipients(SmsMessageRecipientsType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new SmsMessageRecipients(SmsMessageRecipientsType.ArrayOfPhoneNumberWithCid)
                    {
                        ArrayOfPhoneNumberWithCid = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<PhoneNumberWithCid>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<PhoneNumberWithCid>), new SmsMessageRecipients(SmsMessageRecipientsType.ArrayOfPhoneNumberWithCid), "ArrayOfPhoneNumberWithCid"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SmsMessageRecipients res = (SmsMessageRecipients)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

                if (res.PhoneNumberWithCid != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PhoneNumberWithCid));
                    return;
                }

                if (res.ArrayOfPhoneNumberWithCid != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfPhoneNumberWithCid));
                    return;
                }
            }

        }

    }
}