//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Components
{
    using Gsmservice.Gateway.Utils;
    
    /// <summary>
    /// SMS type according to the table<br/>
    /// 
    /// <remarks>
    ///     <br/>
    /// |type|Description|<br/>
    /// |----|-----------|<br/>
    /// |  1 |  SMS PRO  |<br/>
    /// |  3 |  SMS ECO  |<br/>
    /// |  4 |  SMS 2WAY |
    /// </remarks>
    /// </summary>
    public enum SmsType
    {
        SmsPro = 1,
        SmsEco = 3,
        SmsTwoWay = 4,
    }

}