//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Requests
{
    using Gsmservice.Gateway.Utils;
    
    public class GetSubaccountDetailsRequest
    {

        /// <summary>
        /// Login of the subaccount (user) to get the data for
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=true,name=user_login")]
        public string UserLogin { get; set; } = default!;
    }
}