//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Requests
{
    using Gsmservice.Gateway.Models.Components;
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class GetSmsPriceRequestBodyType
    {
        private GetSmsPriceRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static GetSmsPriceRequestBodyType Sms { get { return new GetSmsPriceRequestBodyType("Sms"); } }
        
        public static GetSmsPriceRequestBodyType ArrayOfSms { get { return new GetSmsPriceRequestBodyType("arrayOfSms"); } }
        
        public static GetSmsPriceRequestBodyType Null { get { return new GetSmsPriceRequestBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(GetSmsPriceRequestBodyType v) { return v.Value; }
        public static GetSmsPriceRequestBodyType FromString(string v) {
            switch(v) {
                case "Sms": return Sms;
                case "arrayOfSms": return ArrayOfSms;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for GetSmsPriceRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((GetSmsPriceRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// To check the price of a single SMS or messages with the same content to multiple recipients, pass in the Request Body a single `Sms` object with the properties of this message. To check the price of multiple messages with different content at the same time, pass in the Request Body an `array` of `Sms` objects with the properties of each message.
    /// </summary>
    [JsonConverter(typeof(GetSmsPriceRequestBody.GetSmsPriceRequestBodyConverter))]
    public class GetSmsPriceRequestBody {
        public GetSmsPriceRequestBody(GetSmsPriceRequestBodyType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Models.Components.Sms? Sms { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<Models.Components.Sms>? ArrayOfSms { get; set; }

        public GetSmsPriceRequestBodyType Type { get; set; }


        public static GetSmsPriceRequestBody CreateSms(Models.Components.Sms sms) {
            GetSmsPriceRequestBodyType typ = GetSmsPriceRequestBodyType.Sms;

            GetSmsPriceRequestBody res = new GetSmsPriceRequestBody(typ);
            res.Sms = sms;
            return res;
        }

        public static GetSmsPriceRequestBody CreateArrayOfSms(List<Models.Components.Sms> arrayOfSms) {
            GetSmsPriceRequestBodyType typ = GetSmsPriceRequestBodyType.ArrayOfSms;

            GetSmsPriceRequestBody res = new GetSmsPriceRequestBody(typ);
            res.ArrayOfSms = arrayOfSms;
            return res;
        }

        public static GetSmsPriceRequestBody CreateNull() {
            GetSmsPriceRequestBodyType typ = GetSmsPriceRequestBodyType.Null;
            return new GetSmsPriceRequestBody(typ);
        }

        public class GetSmsPriceRequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(GetSmsPriceRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new GetSmsPriceRequestBody(GetSmsPriceRequestBodyType.Sms)
                    {
                        Sms = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Models.Components.Sms>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Models.Components.Sms), new GetSmsPriceRequestBody(GetSmsPriceRequestBodyType.Sms), "Sms"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new GetSmsPriceRequestBody(GetSmsPriceRequestBodyType.ArrayOfSms)
                    {
                        ArrayOfSms = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<Models.Components.Sms>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<Models.Components.Sms>), new GetSmsPriceRequestBody(GetSmsPriceRequestBodyType.ArrayOfSms), "ArrayOfSms"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                GetSmsPriceRequestBody res = (GetSmsPriceRequestBody)value;
                if (GetSmsPriceRequestBodyType.FromString(res.Type).Equals(GetSmsPriceRequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Sms != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Sms));
                    return;
                }
                if (res.ArrayOfSms != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfSms));
                    return;
                }

            }

        }

    }
}