//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Requests
{
    using Gsmservice.Gateway.Models.Components;
    using Gsmservice.Gateway.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SendSmsRequestBodyType
    {
        private SendSmsRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }

        public static SendSmsRequestBodyType SmsMessage { get { return new SendSmsRequestBodyType("SmsMessage"); } }

        public static SendSmsRequestBodyType ArrayOfSmsMessage { get { return new SendSmsRequestBodyType("arrayOfSmsMessage"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SendSmsRequestBodyType v) { return v.Value; }
        public static SendSmsRequestBodyType FromString(string v) {
            switch(v) {
                case "SmsMessage": return SmsMessage;
                case "arrayOfSmsMessage": return ArrayOfSmsMessage;
                default: throw new ArgumentException("Invalid value for SendSmsRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SendSmsRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// To send a single SMS or messages with the same content to multiple recipients, please use `SendSmsRequestBody.CreateSmsMessage()` method with a single `SmsMessage` object with the properties of this message. To send multiple messages with different content at the same time, please use `SendSmsRequestBody.CreateArrayOfSmsMessage()` method passing to it `List&lt;SmsMessage&gt;` with the properties of each message.
    /// </summary>
    [JsonConverter(typeof(SendSmsRequestBody.SendSmsRequestBodyConverter))]
    public class SendSmsRequestBody
    {
        public SendSmsRequestBody(SendSmsRequestBodyType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public SmsMessage? SmsMessage { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<SmsMessage>? ArrayOfSmsMessage { get; set; }

        public SendSmsRequestBodyType Type { get; set; }
        public static SendSmsRequestBody CreateSmsMessage(SmsMessage smsMessage)
        {
            SendSmsRequestBodyType typ = SendSmsRequestBodyType.SmsMessage;

            SendSmsRequestBody res = new SendSmsRequestBody(typ);
            res.SmsMessage = smsMessage;
            return res;
        }
        public static SendSmsRequestBody CreateArrayOfSmsMessage(List<SmsMessage> arrayOfSmsMessage)
        {
            SendSmsRequestBodyType typ = SendSmsRequestBodyType.ArrayOfSmsMessage;

            SendSmsRequestBody res = new SendSmsRequestBody(typ);
            res.ArrayOfSmsMessage = arrayOfSmsMessage;
            return res;
        }

        public class SendSmsRequestBodyConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SendSmsRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new SendSmsRequestBody(SendSmsRequestBodyType.SmsMessage)
                    {
                        SmsMessage = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SmsMessage>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SmsMessage), new SendSmsRequestBody(SendSmsRequestBodyType.SmsMessage), "SmsMessage"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new SendSmsRequestBody(SendSmsRequestBodyType.ArrayOfSmsMessage)
                    {
                        ArrayOfSmsMessage = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<SmsMessage>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<SmsMessage>), new SendSmsRequestBody(SendSmsRequestBodyType.ArrayOfSmsMessage), "ArrayOfSmsMessage"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SendSmsRequestBody res = (SendSmsRequestBody)value;

                if (res.SmsMessage != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SmsMessage));
                    return;
                }

                if (res.ArrayOfSmsMessage != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfSmsMessage));
                    return;
                }
            }

        }

    }
}