//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway.Models.Requests
{
    using Gsmservice.Gateway.Utils;
    
    public class SetDefaultSenderRequest
    {

        /// <summary>
        /// Sender name to set as default
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=sender")]
        public string Sender { get; set; } = default!;
    }
}