workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Client -OAS:
        inputs:
            - location: ..\..\..\app\libs\restApi\openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/intermedia/gsmservice-pl/client--oas
targets:
    client:
        target: csharp
        source: Client -OAS
        publish:
            nuget:
                apiKey: $nuget_api_key
