//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gsmservice.Gateway
{
    using Gsmservice.Gateway.Hooks;
    using Gsmservice.Gateway.Models.Components;
    using Gsmservice.Gateway.Models.Errors;
    using Gsmservice.Gateway.Utils;
    using Gsmservice.Gateway.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading.Tasks;

    /// <summary>
    /// Messaging Gateway SzybkiSMS.pl<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// This package includes Messaging SDK for C# to send SMS and MMS messages directly from your app via <a href="https://szybkisms.pl">https://szybkisms.pl</a> messaging platform.<br/>
    /// <br/>
    /// *Client* class is used to initialize SDK environment.<br/>
    /// <br/>
    /// Please initialize it this way:<br/>
    /// <br/>
    /// ```<br/>
    /// using Gsmservice.Gateway;<br/>
    /// <br/>
    /// var sdk = new Client(bearer: &quot;YOUR API ACCESS TOKEN&quot;);<br/>
    /// ```<br/>
    /// <br/>
    /// If you want to use a Sandbox test system please initialize it as follows:<br/>
    /// <br/>
    /// ```<br/>
    /// var sdk = new Client(bearer: &quot;YOUR API ACCESS TOKEN&quot;, null, SDKConfig.Server.Sandbox);<br/>
    /// ```
    /// </remarks>
    /// 
    /// <see href="https://szybkisms.pl">SzybkiSMS.pl</see>
    /// </summary>
    public interface IClient
    {
        public IAccounts Accounts { get; }
        public IOutgoing Outgoing { get; }
        public IIncoming Incoming { get; }
        public ICommon Common { get; }
        public ISenders Senders { get; }
    }


    /// <summary>
    /// Messaging Gateway SzybkiSMS.pl<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// This package includes Messaging SDK for C# to send SMS and MMS messages directly from your app via <a href="https://szybkisms.pl">https://szybkisms.pl</a> messaging platform.<br/>
    /// <br/>
    /// *Client* class is used to initialize SDK environment.<br/>
    /// <br/>
    /// Please initialize it this way:<br/>
    /// <br/>
    /// ```<br/>
    /// using Gsmservice.Gateway;<br/>
    /// <br/>
    /// var sdk = new Client(bearer: &quot;YOUR API ACCESS TOKEN&quot;);<br/>
    /// ```<br/>
    /// <br/>
    /// If you want to use a Sandbox test system please initialize it as follows:<br/>
    /// <br/>
    /// ```<br/>
    /// var sdk = new Client(bearer: &quot;YOUR API ACCESS TOKEN&quot;, null, SDKConfig.Server.Sandbox);<br/>
    /// ```
    /// </remarks>
    /// 
    /// <see href="https://szybkisms.pl">SzybkiSMS.pl</see>
    /// </summary>
    public class Client: IClient
    {
        public SDKConfig SDKConfiguration { get; private set; }

        private const string _language = Constants.Language;
        private const string _sdkVersion = Constants.SdkVersion;
        private const string _sdkGenVersion = Constants.SdkGenVersion;
        private const string _openapiDocVersion = Constants.OpenApiDocVersion;
        public IAccounts Accounts { get; private set; }
        public IOutgoing Outgoing { get; private set; }
        public IIncoming Incoming { get; private set; }
        public ICommon Common { get; private set; }
        public ISenders Senders { get; private set; }

        public Client(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Accounts = new Accounts(SDKConfiguration);

            Outgoing = new Outgoing(SDKConfiguration);

            Incoming = new Incoming(SDKConfiguration);

            Common = new Common(SDKConfiguration);

            Senders = new Senders(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="bearer">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="bearerSource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="server">The server to use from the predefined server list.</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default SpeakeasyHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        public Client(string? bearer = null, Func<string>? bearerSource = null, SDKConfig.Server? server = null, string? serverUrl = null, Dictionary<string, string>? urlParams = null, ISpeakeasyHttpClient? client = null, RetryConfig? retryConfig = null)
        {

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Gsmservice.Gateway.Models.Components.Security>? _securitySource = null;

            if(bearerSource != null)
            {
                _securitySource = () => new Gsmservice.Gateway.Models.Components.Security() { Bearer = bearerSource() };
            }
            else if(bearer != null)
            {
                _securitySource = () => new Gsmservice.Gateway.Models.Components.Security() { Bearer = bearer };
            }

            SDKConfiguration = new SDKConfig(client)
            {
                ServerName = server,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Accounts = new Accounts(SDKConfiguration);

            Outgoing = new Outgoing(SDKConfiguration);

            Incoming = new Incoming(SDKConfiguration);

            Common = new Common(SDKConfiguration);

            Senders = new Senders(SDKConfiguration);
        }

        private void InitHooks()
        {
            string preHooksUrl = SDKConfiguration.GetTemplatedServerUrl();
            var (postHooksUrl, postHooksClient) = SDKConfiguration.Hooks.SDKInit(preHooksUrl, SDKConfiguration.Client);
            var config = SDKConfiguration;
            if (preHooksUrl != postHooksUrl)
            {
                config.ServerUrl = postHooksUrl;
            }
            config.Client = postHooksClient;
            SDKConfiguration = config;
        }

        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new SpeakeasyHttpClient());

            public SDKBuilder() { }

            public SDKBuilder WithServer(SDKConfig.Server server)
            {
                _sdkConfig.ServerName = server;
                return this;
            }

            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }

            public SDKBuilder WithBearerSource(Func<string> bearerSource)
            {
                _sdkConfig.SecuritySource = () => new Gsmservice.Gateway.Models.Components.Security() { Bearer = bearerSource() };
                return this;
            }

            public SDKBuilder WithBearer(string bearer)
            {
                _sdkConfig.SecuritySource = () => new Gsmservice.Gateway.Models.Components.Security() { Bearer = bearer };
                return this;
            }

            public SDKBuilder WithClient(ISpeakeasyHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            public Client Build()
            {
              return new Client(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}